name = "ai-chat-workers"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "ai-chat-workers"
vars = { ENVIRONMENT = "production" }

[env.staging]
name = "ai-chat-workers-staging"
vars = { ENVIRONMENT = "staging" }

# 环境变量需要通过 wrangler secret 命令设置
# 设置 Anthropic API 密钥（二选一）:
# wrangler secret put ANTHROPIC_API_KEY
# wrangler secret put CLAUDE_API_KEY
# 
# 其他可选配置:
# wrangler secret put CORS_ORIGINS
